### ISSUE TITLE
🏷️ » new icons: python variants + project folders + others

### ISSUE THREAD

**Issue by lucas-labs** [lucodear/lucodear-icons#18]
#### Misc
- [x] pytest conf icon
- [x] ruff (.ruff.toml config file)

#### *.py icons

by name:

- [x] main.py `#e57373`
- [x] `__init__py`

Pest Pack (folder Based files):

- [x] aggregates/py `#7e57c2`
- [x] controllers/py `#1e88e5`
- [x] dto/py `#ec407a`
- [x] middleware/py
- [x] models/py `#ab47bc`
- [x] providers/py `#00acc1`
- [x] dicts/py `#ffa726` [lines]
- [x] abc/py `#b0bec5` [lines]
- [x] pydantic/py `#f06292`
- [x] services/py `#ffa726`
- [x] tests/py `#00bfa5`
- [x] tools/py `#0277bd`

### folders
- [x] azure folder
- [x] osb (oracle) folder

llm stuff
- [x] `llm`, `ai` folder
- [x] `agent` folder
- [x] `chains` folder
