### ISSUE TITLE
🏷️ » new icons: extend react pack with variants

### ISSUE THREAD

**Issue by lucas-labs** [lucodear/lucodear-icons#22]
Add variants to react tsx and jsx files

- [ ] `app.[tsx|jsx]` `#009688`
- [ ] `page.[tsx|jsx]` `#7afff8`
- [ ] `layout.[tsx|jsx]` `#a1887f`
- [ ] `component.[tsx|jsx]` `#fffb72`
- [ ] `section.[tsx|jsx]` `#bcff74`
- [ ] `hook.[tsx|jsx]` `#ce88ff`
- [ ] `context.[tsx|jsx]` `#00897b`
