### ISSUE TITLE
📍 » pixel-perfect : pkiefs icons patch - Folders Track

### ISSUE THREAD

**Issue by lucas-labs** [lucodear/lucodear-icons#40]
Patch most useed pkief icons to make them pixel perfect:

- [x] src #36
- [x] git #36
- [x] gitlab #36
- [x] github #36
- [x] dist #36
- [x] task #36
- [x] taskfile #36
- [x] logs #36
- [x] common/shared #36
- [x] api #36
- [x] command/cli #36
- [x] utils #36
- [x] helpers #36
- [x] images #36
- [x] i18n #36
- [x] scripts #36
- [x] admin #42 
- [x] app #42 
- [x] json #42 
- [x] custom #42 
- [x] test #42 
- [x] functions #42 
- [x] core #42 
- [x] storybook #42 
- [x] guard #42 
- [x] environment #42 
- [x] database (copy from lucodear models, different color!) #42 
- [x] routes #42 
- [x] sass #42 
- [x] css #42 
- [x] hook #42
- [x] lib #44
- [x] public #44
- [x] vercel #44
- [x] stack #44
- [x] next #44
- [x] server #44
- [x] tools #44
- [x] layout #44
- [x] template #44
- [x] mock #44
- [x] typescript #44
- [x] javascript #44
- [x] node (copy from taskfile, different color) #44
- [x] pipe (same as lucodear transformation, different color) #44
- [x] theme #44
- [x] font #44
- [x] views #44
- [x] meta (similar to utils) #44
- [x] resource (same as meta, diff colors) #44
- [x] docs #44
- [x] project #44
- [x] job #44
- [x] vscode #44
- [x] markdown #44
- [x] class #44
- [x] robot #44
- [x] mobile #44
- [x] import #44
- [x] android #44
- [x] context #44
- [x] mail #44
- [x] mappings #44
- [x] docker #44
- [x] client #44
- [x] include #44
- [x] examples #44
- [x] animation #44
- [x] debug #44
- [x] interface #44
- [x] ios #44
- [x] jinja #44
- [x] other #44
- [x] queue #44
- [x] java #44
- [x] packages #44
- [x] keys #44
- [x] pdf #44
- [x] svg #44
- [x] dump #44
- [x] target #44
- [x] aws #44
- [x] enum #44
- [x] plugin #44
- [x] azure-pipelines #44
- [x] kubernetes #44
- [x] prisma #44
- [x] base #44
- [x] error #44
- [x] private #44
- [x] temp #44
- [x] batch #44
- [x] event #44
- [x] less #44
- [x] benchmark #44
- [x] proto #44
- [x] linux #44
- [x] export #44
- [x] firebase #44
- [x] ci #44
- [x] macos #44
- [x] circleci #44
- [x] upload #44
- [x] cluster #44
- [x] generator #44
- [x] messages #44
- [x] resolver #44
- [x] verdaccio #44
- [x] video #44
- [x] config #44
- [x] global #44
- [x] connection #44
- [x] constant #44
- [x] rules #44
- [x] container #44
- [x] gulp #44
- [x] netlify #44
- [x] secure #44
- [x] home #44
- [x] windows #44
- [x] yarn #44
- [x] sublime #44
- [x] supabase #44
- [x] angular #44
- [x] ansible #44
- [x] apollo #44
- [x] archive #44
- [x] audio #44
- [x] aurelia #44
- [x] bower #44
- [x] buildkite #44
- [x] cart #44
- [x] changesets #44
- [x] cobol #44
- [x] components #44
- [x] content #44
- [x] contract #44
- [x] controller #44
- [x] coverage #44
- [x] cypress #44
- [x] decorators #44
- [x] delta #44
- [x] download #44
- [x] expo #44
- [x] fastlane #44
- [x] flow #44
- [x] gamemaker #44
- [x] godot #44
- [x] gradle #44
- [x] graphql #44
- [x] husky #44
- [x] intellij #44
- [x] lottie #44
- [x] lua #44
- [x] mercurial #44
- [x] middleware #44
- [x] mjml #44
- [x] mojo #44
- [x] moon #44
- [x] ngrx-actions #44
- [x] ngrx-effects #44
- [x] ngrx-entities #44
- [x] ngrx-reducer #44
- [x] ngrx-selectors #44
- [x] ngrx-state #44
- [x] ngrx-store #44
- [x] nuxt #44
- [x] pdm #44
- [x] php #44
- [x] phpmailer #44
- [x] plastic #44
- [x] python #44
- [x] quasar #44
- [x] react-components #44
- [x] redux-actions #44
- [x] redux-reducer #44
- [x] redux-selector #44
- [x] redux-store #44
- [x] review #44
- [x] root #44
- [x] scala #44
- [x] serverless #44
- [x] shader #44
- [x] stencil #44
- [x] stylus #44
- [x] svelte #44
- [x] syntax #44
- [x] terraform #44
- [x] unity #44
- [x] update #44
- [x] vm #44
- [x] vue-directives #44
- [x] vue #44
- [x] vuepress #44
- [x] vuex-store #44
- [x] wakatime #44
- [x] webpack #44
- [x] wordpress #44

**Comment by lucas-labs** [comment]
Completed.
